### ISSUE TITLE
docs: How is this tool supposed to be installed?

### ISSUE THREAD

**Issue by anacasner** [talos-systems/conform#119]
Hi there, I'm trying to use this tool but I couldn't find instructions on how to install it - do I clone this repo, do I need to run some commands...?

Any pointers are greatly appreciated!

Thank you,
Ana

**Comment by andrewrynhard** [comment]
Hey @anacasner. Sorry for the delayed response. To install it you will need a valid Golang setup. Then you run

```
go get github.com/autonomy/conform
````

That _should_ be enough to get you going!

**Comment by andrewrynhard** [comment]
@anacasner I just made a new release with some precompiled binaries: https://github.com/autonomy/conform/releases/tag/v0.1.0-alpha.11
