### ISSUE TITLE
docs: how to use conform

### ISSUE THREAD

**Issue by lhohan-cb** [talos-systems/conform#146]
How do I install this tool please?

Found [this issue](https://github.com/talos-systems/conform/issues/119) but was closed.

Would be good to add installation instruction to the README.

**Comment by andrewrynhard** [comment]
Hi @lhohan-cb. Thanks for the suggestion. I will add directions to the README. To install simply download the binary from a release https://github.com/talos-systems/conform/releases and place it in your PATH. You can use the config in the example as a starting point. Place it in the top level of the git repo you would like conform. Let me know if you have any troubles. Thanks!

**Comment by Herve-M** [comment]
I join the point of the `how to use it`.
After playing with it, it seems that it can't be used locally (to enforce) with git hooks like `commit-msg` and it only work on the last commit. 

What was/are the usage scenarios?

**Comment by andrewrynhard** [comment]
@Herve-M 

to install:

```
go get github.com/talos-systems/conform
```

to setup the git hook:

```
cat <<EOF | tee .git/hooks/commit-msg
#!/bin/sh

conform enforce --commit-msg-file \$1
EOF
chmod +x .git/hooks/commit-msg
```

I'll update the README now

**Comment by andrewrynhard** [comment]
https://github.com/talos-systems/conform/pull/154

**Comment by Herve-M** [comment]
@andrewrynhard Perfect! I didn't check all the options in the help, my bad & shame!

**Comment by andrewrynhard** [comment]
The README should have enough to get started.
