### ISSUE TITLE
issue: Conform gh-action doesn't fail when check fails 

### ISSUE THREAD

**Issue by jwnx** [talos-systems/conform#149]
Conform logs checks as failed, but doesn't report the action as failed. This is a problem because when using conform as part of a larger Github Actions pipeline, it requires reviewers to check workflow logs to ensure all conform checks passed.

**Comment by andrewrynhard** [comment]
@jwnx Thanks for reporting. That certainly isn't the expected behavior. Does conform report success at all, or are the statuses on the PR missing?

**Comment by jwnx** [comment]
Hi @andrewrynhard (:
Thanks for answering! Conform reports sucess. Here's a screenshot:
![screenshot-conform](https://user-images.githubusercontent.com/4687817/70393215-a1621480-19c6-11ea-8cfa-876882a50325.png)

**Comment by andrewrynhard** [comment]
@jwnx What about on the PR? It should be created PR statuses.

**Comment by andrewrynhard** [comment]
@jwnx Looks like I just need to cut another release: https://github.com/talos-systems/conform/commit/365c592227c7ecadf52a8d22db22fca0dea015a0

**Comment by andrewrynhard** [comment]
@jwnx I just created a release to the marketplace. It should have the fix you need. I had to get things in order so that I could publish to the marketplace, so things may have changed. Give it a test and let me know 👍.

**Comment by jwnx** [comment]
It works now! Tested on `docker://autonomy/conform:v0.1.0-alpha.17` (:
