### ISSUE TITLE
How do I build locally to run confrom?

### ISSUE THREAD

**Issue by PachVerb** [talos-systems/conform#170]
Build according to readme, I can't build well。 If posterity knows, please tell me, thanks

**Comment by andrewrynhard** [comment]
Can you share the exact command along with the logs?

**Comment by Isakofff** [comment]
You can use Docker container
docker run --rm --workdir /github/workspace -v "/var/run/docker.sock":"/var/run/docker.sock" -v $(pwd):"/github/workspace" autonomy/conform:v0.1.0-alpha.20-6-g73f334a

**Comment by PachVerb** [comment]
> You can use Docker container
> `docker run --rm --workdir /github/workspace -v "/var/run/docker.sock":"/var/run/docker.sock" -v $(pwd):"/github/workspace" autonomy/conform:v0.1.0-alpha.20-6-g73f334a`

Good, thank you very much
