### ISSUE TITLE
conform version discrepancy in `action.yaml`

### ISSUE THREAD

**Issue by artem-bardeenai** [talos-systems/conform#179]
Hello,

`action.yaml` is currently [referencing](https://github.com/talos-systems/conform/blob/5a75e96171ef6aaaebecfced193df379296e03d7/action.yml#L12) a Docker image containing an older release (`v0.1.0-alpha.17`) of `conform`. 

This same version is also referenced from [v0.1.0-alpha.20](https://github.com/artem-bardeenai/conform/releases/tag/v0.1.0-alpha.20) tag. Not sure if it is intentional, but it is somewhat confusing. People might think they are using `v0.1.0-alpha.20` by means of including `- uses: talos-systems/conform@v0.1.0-alpha.20` in their GitHub workflow jobs when in fact the `v0.1.0-alpha.17` image is pulled. I realized this after noticing that some important features (such as spellchecking) were seemingly missing from `conform`. 

Cheers,
Artem.

**Comment by andrewrynhard** [comment]
@artem-bardeenai Good catch. This is just a mistake. I can fix in the next release.
