### ISSUE TITLE
how we can check if JIra Ticket is added with commit or not

### ISSUE THREAD

**Issue by NehaSachan** [talos-systems/conform#180]
So i need a config setting which let me hold if with all correct commit message, do i also added the Jira TIcketID.

As i need to enforce that too in place.

Sample:
"feat: **JIRA:XXXX**  Added authentication code
With creation of OAuth"

**Comment by andrewrynhard** [comment]
@NehaSachan we only support regex in the scope, but it could be expanded to the description. I can't promise we can get to that soon, but PRs are welcome!

**Comment by flyhard** [comment]
I created a PR. Slight modification to the request since Jira tags are normally are like this: [PROJ-1234]
