### ISSUE TITLE
JIRA issue cannot be used together with scopes

### ISSUE THREAD

**Issue by olivernybroe** [talos-systems/conform#185]
The newly added JIRA issue does not work when using scopes also. 

E.G. we tried to have the following commit message
```
ci(static-analysis): [JIRA-1005] add conform

Adds conform configuration file together with an github action for it
```

**Comment by andrewrynhard** [comment]
I can get this fixed in the AM.

**Comment by olivernybroe** [comment]
No rush, really appreciate the work you guys are doing here 👍
