### ISSUE TITLE
JIRA issue forced square brackets

### ISSUE THREAD

**Issue by olivernybroe** [talos-systems/conform#186]
Right now the JIRA issue is forcing square brackets, which in our opinion is just bloating the commit with unneeded characters.

This is what we want it to look like
```
ci: JIRA-1005 add conform

Adds conform configuration file together with an github action for it
```

However we are forced to do 
```
ci: [JIRA-1005] add conform

Adds conform configuration file together with an github action for it
```

**Comment by andrewrynhard** [comment]
Seems reasonable to me. We can probably make the brackets optional.

**Comment by olivernybroe** [comment]
@andrewrynhard Sounds awesome 👍

**Comment by andrevalentin** [comment]
@andrewrynhard just piling on here, really appreciate the work! Looking forward to seeing this and #185 resolved 🙌
