### ISSUE TITLE
ci: missing golangci-lint run

### ISSUE THREAD

**Issue by alex1989hu** [talos-systems/conform#193]
The CI does not have any `golangci-lint` job.

**Comment by alex1989hu** [comment]
Created a PR https://github.com/talos-systems/conform/pull/194 which fixes linter errors to let you easily add `golangci-lint` job

**Comment by smira** [comment]
Closed via #194

**Comment by alex1989hu** [comment]
> Closed via #194

Actually that PR does not add CI job to drone CI

**Comment by smira** [comment]
@alex1989hu sorry!

**Comment by alex1989hu** [comment]
Can it work?

```patch
diff --git a/.drone.yml b/.drone.yml
index 3dcbf4a..a63fc91 100644
--- a/.drone.yml
+++ b/.drone.yml
@@ -26,6 +26,15 @@ steps:
       - name: dockersock
         path: /var/run

+  - name: lint
+    image: golangci/golangci-lint:v1.32.2
+    pull: always
+    commands:
+      - golangci-lint run --config hack/golangci-lint.yaml
+    volumes:
+      - name: dockersock
+        path: /var/run
+
   - name: conform
     image: autonomy/build-container:latest
     pull: always
```

PS.: the image is huge: `858MB`

**Comment by smira** [comment]
I don't think we need that, feels like `make test` does that, as in the Dockerfile it goes to `hack/test.sh --all`

**Comment by alex1989hu** [comment]
Oh, really! I can verify that; probably missed that.
