### ISSUE TITLE
Jira project centos is not a valid jira project

### ISSUE THREAD

**Issue by Isakofff** [talos-systems/conform#197]
We have such .conform.yaml config
<img width="296" alt="Снимок экрана 2021-01-20 в 19 30 41" src="https://user-images.githubusercontent.com/31091163/105175174-28843480-5b56-11eb-97e9-67eac3649d45.png">
But when we create such commit message
`feat: [CSE-2756] add crowdstrike package for centos-7_arm64`
We have an error
<img width="982" alt="Снимок экрана 2021-01-20 в 19 29 10" src="https://user-images.githubusercontent.com/31091163/105175284-48b3f380-5b56-11eb-980a-f3c299ffbd07.png">

Why the tool thinks that centos-7_arm64 is about Jira ticket?

Everything is fine only with such commit message (centos7 without dash)
`feat: [CSE-2756] add crowdstrike package for centos7_arm64`

**Comment by andrewrynhard** [comment]
Sounds like the regex needs to be update.
