### ISSUE TITLE
Following semantic version for conform

### ISSUE THREAD

**Issue by maulik13** [talos-systems/conform#201]
I see that the version of conform itself is still alpha. Is this intentional? When do you plan to bump the version which is not a prerelease?

Thanks.

P.S. Great job with the tool  :)

**Comment by andrewrynhard** [comment]
@maulik13 its really just because we aren't in any rush to graduate since we are still getting feedback from the community. That being said, we use this in production. We haven't really thought through when it would no longer be alpha, but we can start to think about that.

**Comment by maulik-vimond** [comment]
@andrewrynhard  I understand. I was just curious about the thought process. It is easier to convince my team (and I suppose others) if the version is not alpha. 

Hopefully you can get to a release version soon.

**Comment by maulik13** [comment]
@andrewrynhard I understand. I was just curious about the thought process. It is easier to convince my team (and I suppose others) if the version is not alpha.

Hopefully you can get to a release version soon.

**Comment by andrewrynhard** [comment]
> @andrewrynhard I understand. I was just curious about the thought process. It is easier to convince my team (and I suppose others) if the version is not alpha.
> 
> 
> 
> Hopefully you can get to a release version soon.

Understandable. Thanks!
