### ISSUE TITLE
pulling talos Golang library, getting error

### ISSUE THREAD

**Issue by NehaSachan** [talos-systems/conform#205]
Hi team,

using below command -
go get -u github.com/talos-systems/conform@v0.1.0-alpha.17

I always get below error -  tried many versions....but its same....

How to solve it??

go: downloading github.com/talos-systems/conform v0.1.0-alpha.17
go: downloading gopkg.in/src-d/go-git.v4 v4.0.0
go: downloading gopkg.in/src-d/go-git.v4 v4.13.1
go: downloading gopkg.in/src-d/go-billy.v4 v4.3.2
go: downloading github.com/src-d/gcfg v1.4.0
go get: gopkg.in/jdkato/prose.v2@v2.0.0-20180825173540-767a23049b9e updating to
	gopkg.in/jdkato/prose.v2@v2.0.0: parsing go.mod:
	module declares its path as: github.com/jdkato/prose/v2
	        but was required as: gopkg.in/jdkato/prose.v2

Please help...

@andrewrynhard @smira  @petersng @andrevalentin

**Comment by AlekSi** [comment]
Please try a newer version. This worked for me:
```
go install -v github.com/talos-systems/conform@v0.1.0-alpha.20
```

**Comment by NehaSachan** [comment]
Great...
It worked like a charm.

Thank you.
